### PR TITLE
Swagger

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by zuphilip** [comment]
Thank you very much, @kba! I will try this out here in my `swagger` fork and not in the `master` fork, i.e. this replaces #1.

**Comment by kba** [comment]
Yes, try it out but keep in mind that this changes the zotero submodule in https://github.com/zuphilip/translation-server/pull/2/commits/569c6597906f6eb6b9f00d40699d3c1d5aadf534, so there's some work to do (either patch here or upstream) before CORS will work.

**Comment by zuphilip** [comment]
Hm.. I cannot follow. The change is to to use [`kba/zotero`](https://github.com/kba/zotero) but this seems for me identical with the normal `zotero/zotero`. I can only confirm that the installation works and the script works. The result suffers still from the CORS problematic.

**Comment by kba** [comment]
Forgot to commit to kba/zotero, sorry. https://github.com/kba/zotero/commit/506d1cc7899032bb35b3f89d9ec075cff24dbe3f

**Pull request merged**
